language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - "rake db:drop RAILS_ENV=test"
  - "rake db:create RAILS_ENV=test"
  - "rake db:migrate"
  - "rake db:seed"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
