# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 041e2ada4d279b4efd0cb5b06cd1ef36f022612306bbbdd85c72e7fbdc816d67b6353e3226c561c22f0714e7de911c11caa9ccb1679c20476cc44da36d969ce7

test:
  secret_key_base: 937eeb7992b6dd298ccb64e1e8523e345f8e6d15e0daae52f51bf537d7dc107875e16d566e22d30c073170106df499c5b52a95409192e7ed2e95f9c29af62248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
